version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_strong_password
      POSTGRES_DB: your_database_name
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent data volume
    restart: unless-stopped
    networks:
      - postgres-net

networks:
  postgres-net:
    external: true  # External network for container access
